language: java

jdk:
  - openjdk8

before_install:
  - docker run -d --name elasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" paulcwarren/elasticsearch:latest

script:
 - mvn test
