milton:
  filesystem_root: /tmp
  exclude_paths:
    - /static
    - /templates
    - /management
    - /webjars

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/webdav
  driverClassName: com.mysql.jdbc.Driver    
spring.jpa.database: MYSQL
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.jpa.properties.hibernate.format_sql: false

security.ignored: true

logging.level.org.springframework.web: INFO
logging.level.org.springframework.boot.context.web: INFO
logging.level.io.milton.http.http11.auth: ERROR
logging.level.org.hibernate.SQL: ERROR
logging.file: /tmp/webdav.log

spring.content:
  filesystem_root: /tmp/spring-gs-content-webdav
