milton:
  filesystem_root: /tmp
  exclude_paths:
    - /static
    - /templates
    - /management
    - /webjars

spring.datasource:
  url: jdbc:mysql://mysql.persi.cf-app.com:3306/webdav
  driverClassName: com.mysql.jdbc.Driver    
spring.jpa.database: MYSQL
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
